# --- General options --- #

# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
url: "https://danielilett.com"
baseurl: ""

# Name of website
title: Daniel Ilett

# Short description of your site
description: Games | Shaders | Tutorials

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Assets: "assetpacks"
  Tutorials: "tutorials"
  Support me: "support"
  About: "aboutme"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Series definitions --- #
series-list:
- series-name: Image Effects
  series-parts: 
    - label: i
      link: https://danielilett.com/2019-04-24-tut1-intro-smo/
    - label: 0
      link: https://danielilett.com/2019-04-27-tut1-0-smo-shader-basics/
    - label: 1
      link: https://danielilett.com/2019-05-01-tut1-1-smo-greyscale/
    - label: 2
      link: https://danielilett.com/2019-05-04-tut1-2-smo-silhouette/
    - label: 3
      link: https://danielilett.com/2019-05-08-tut1-3-smo-blur/
    - label: 4
      link: https://danielilett.com/2019-05-11-tut1-4-smo-edge-detect/
    - label: 5
      link: https://danielilett.com/2019-05-15-tut1-5-smo-retro/
    - label: 6
      link: https://danielilett.com/2019-05-18-tut1-6-smo-painting/
    - label: 7
      link: https://danielilett.com/2019-05-22-tut1-7-smo-end/
- series-name: Cel-shading
  series-parts:
    - label: i
      link: https://danielilett.com/2019-05-29-tut2-intro/
    - label: 0
      link: https://danielilett.com/2019-06-01-tut2-0-lighting-models/
    - label: 1
      link: https://danielilett.com/2019-06-05-tut2-1-diffuse/
    - label: 2
      link: https://danielilett.com/2019-06-08-tut2-2-cel-shading/
    - label: 3
      link: https://danielilett.com/2019-06-12-tut2-3-fresnel/
    - label: 4
      link: https://danielilett.com/2019-06-15-tut2-4-edge-outline/
    - label: 5
      link: https://danielilett.com/2019-06-23-tut2-5-cel-shading-end/
- series-name: Unity Tips
  series-parts:
    - label: 1
      link: https://danielilett.com/2019-08-05-unity-tips-1-garbage-collection/
    - label: 2
      link: https://danielilett.com/2019-08-20-unity-tips-2-coroutines/
    - label: 3
      link: https://danielilett.com/2019-09-08-unity-tips-3-interpolation/
    - label: 4
      link: https://danielilett.com/2019-10-07-unity-tips-4-scriptableobjects/
    - label: 5
      link: https://danielilett.com/2019-10-26-unity-tips-5-persistent-data/
- series-name: Ultra Effects
  series-parts:
    - label: i
      link: https://danielilett.com/2019-09-18-tut3-intro-ultra/
    - label: 1
      link: https://danielilett.com/2019-10-17-tut3-1-something-fishy/
    - label: 2
      link: https://danielilett.com/2019-10-22-tut3-2-sinking-feeling/
    - label: 3
      link: https://danielilett.com/2019-10-30-tut3-3-tiling-trouble/
    - label: 4
      link: https://danielilett.com/2019-11-05-tut3-4-next-dimension/
    - label: 5
      link: https://danielilett.com/2019-11-20-tut3-5-filmic-filters/
    - label: 6
      link: https://danielilett.com/2019-11-26-tut3-6-chromatic-course/
    - label: 7
      link: https://danielilett.com/2020-02-12-tut3-7-vintage-video/
    - label: 8
      link: https://danielilett.com/2020-02-19-tut3-8-crazy-kaleidoscopes/
    - label: 9
      link: https://danielilett.com/2020-02-26-tut3-9-obra-dithering/
    - label: 10
      link: https://danielilett.com/2020-03-04-tut3-10-dungeon-drawing/
- series-name: Portals
  series-parts:
    - label: i
      link: https://danielilett.com/2019-12-01-tut4-intro-portals/
    - label: 1
      link: https://danielilett.com/2019-12-11-tut4-1-spyro-skyboxes/
    - label: 2
      link: https://danielilett.com/2019-12-14-tut4-2-portal-rendering/
    - label: 3
      link: https://danielilett.com/2019-12-18-tut4-3-matrix-matching/
    - label: 4
      link: https://danielilett.com/2020-01-03-tut4-4-portal-momentum/
    - label: 5
      link: https://danielilett.com/2020-01-12-tut4-5-placing-portals/
    - label: 6
      link: https://danielilett.com/2020-01-19-tut4-6-portal-recursion/

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-link-col: "#221144"

# Use a dark mode?
dark-enabled: false

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Daniel Ilett

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  # rss: true
  github: daniel-ilett
  twitter: daniel_ilett
  reddit: daniel_ilett
  linkedin: daniel-ilett-548871106
  itch: danielilett
  patreon: danielilett

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-139156679-1"

# --- Misc --- #

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 30

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/London"
markdown: kramdown
mathjax: true
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 10

kramdown:
  input: GFM
  parse_block_html: true

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true
      pdf: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
